export ADD_TODO = 'ADD_TODO';

export DELETE_TODO = 'DELETE_TODO';

export EDIT_TODO = 'EDIT_TODO';

export COMPLETE_TODO = 'COMPLETE_TODO';

export COMPLETE_ALL = 'COMPLETE_ALL';

export CLEAR_COMPLETED = 'CLEAR_COMPLETED';